### ISSUE TITLE
Script may be able to just run independent of IFTTT

### ISSUE THREAD

**Issue by johnjacobkenny** [abhinavdc/cowin-pinger#2]
I guess many of the 18+ people will be working on their computers, so some kind of notification on desktop without IFTTT would be great

**Comment by abhinavdc** [comment]
I have been thinking about a way to send a notification from the terminal itself and something just popped up in mind. When a slot is found playing a beep sound would be enough to alert the user, no need to send a push notification.

I'll be integrating that feature soon so that you don't need IFTTT to make use of this tool.
