### ISSUE TITLE
IFTTT doubts

### ISSUE THREAD

**Issue by msnitish** [abhinavdc/cowin-pinger#21]
#### Could add few more points about what this IFTTT is all about and how it works ? [ just 2 lines will suffice for beginners ]
 I went through their website but could not understand anything. They are providing all kinds of services.

**Comment by abhinavdc** [comment]
IFTTT is an app/service that lets you connect two different services that wouldn't be normally be possible. For example take the Philips Hue service and Weather service in  IFTTT. Using these two services we can add an **applet** in IFTTT to automate stuff like setting the the Philips Hue bulb in your home to change color to red and blink three times when it's about to rain. IFTTT acts as a bridge between the two services here and makes it possible to automate many stuff. Take another example, you can connect the Facebook service and Amazon Echo service in IFTTT to get a notification on your Echo when you get a new friend request in FB. You can even save all the Photos you get tagged in FB to a folder in your google drive using the FB and Google Drive service of IFTTT. There are lots of pre built applets like the ones I just mentioned or we can make our own applets to connect any service that we want, given that the service is available in IFTTT.

In our case for _cowin-pinger_ we have connected two services called **Webhook** and **Notifications** services in IFTTT. This helps us to call an API endpoint provided by the Webhook service of IFTTT to get a notification on your phone through the IFTTT app on your phone. IFTTT was used here just because that was the easiest way to enable push notification on the phone without having to code all that. _Cowin-pinger_ works without IFTTT, you only need IFTTT if you want to get notification on your mobile when the script finds a slot.

**Comment by abhinavdc** [comment]
Have added a link to this issue in the README.
