### ISSUE TITLE
isSlotAvailable  variable somewhere becomes true even when the cowin site has no free slot

### ISSUE THREAD

**Issue by Bhartendu-Kumar** [abhinavdc/cowin-pinger#24]
I have replaced the "notification in IFTTT" through this script with "VoIP call in IFTTT". So, I can see the text when the webhook fires the event, but at 0:00am I am getting the VoIP call which is the "then this" part of IFTTT in my case.

So, I am thinking the isSlotAvailable variable somehow becomes true, due to either no response from api server or the date variable change, or don't know maybe something

**Comment by Bhartendu-Kumar** [comment]
To add further on it, it wrongly notified even after this incident and the time was 11:00am not even 0:00am.

Had to close the script and re-run to stop continuous notification (keep alive was true).

Checking on cowin site, there was no slot

**Comment by abhinavdc** [comment]
I might have some idea about why this could be happening. I have ran into a similar issue and it happened at midnight right after 00:00 hrs. That was because the script was calling the API for previous date's slots. The Cowin API seems to provide erroneous results if you are searching for a date earlier than the current date. This could explain the reason for your first issue as that will be fixed if you stop and start the pinger which will then take the new date when running. 

But can't figure out why this could happen at 11:00 AM. That could be a separate issue as well. But I will anyway add a fix for this bug so that the script will re evaluate the current date on every iteration. So you shouldn't have to stop and run the script after 11:59 PM.

**Comment by Bhartendu-Kumar** [comment]
@abhinavdc  thank you very much!

yes great to spot that logic. On an already running script, the date is that of the previous day. and hence the query is causing error. 
But this could provide a way to analyse your if-else ladder there which is allowing the valid cases, but at the same time a few invalid cases. So, the if-else is not catching all the invalid cases.

Either that might solve the 11:00 am bug too. Because that was also solved by stopping and rerunning the script. 

Else one probable explanation be we are using the public API that has the cached data but the logged-in version of cowin.gov.in uses real-time data, making inconsistencies.

But I am not convinced myself that this be the case, as re-running stopped the issue and also the not-logged in interface of cowin.gov.in that uses the same public API also showed the same slot information that the logged in version did.

**Comment by abhinavdc** [comment]
@Bhartendu-Kumar I have added the fix for your issue. If you spot this bug again please let me know. There could be inconsistencies due to the caching of the API's too like you said but there isn't anything we can do to fix that.
